### ISSUE TITLE
Possible Handle-leak.

### ISSUE THREAD

**Issue by lordnn** [agruzdev/FreeImageRe#15]
Здесь подразумевается, что если есть указатель, то `AddNode()` добавит загруженный плагин в список и уже сам плагин будет контролировать выгрузку DLL иначе же DLL выгружается. Но если посмотреть исходники, то окажется что AddNode() может и не добавить плагин к списку и произойдёт Handle-leak 
https://github.com/agruzdev/FreeImageRe/blob/9326f8fdcfe39df13de287023e04259f44e67668/Source/FreeImage/Plugin.cpp#L306-L310

**Comment by lordnn** [comment]
P.S. Можно посмотреть как написано в `FreeImage_RegisterExternalPlugin()`

**Comment by agruzdev** [comment]
Fixed in the PR #14
